name: Update

on:
  push:
  schedule:
    - cron: 0 20 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Build
      run: |
        wget https://github.com/tokumeikoi/aurora/releases/latest/download/aurora -O ./TCat
        wget https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip -O ./TCat.zip
    - name: Step 3 - Release
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update
